{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default .Release.Name .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: mal-account-service
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.aws.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsaRoleArn | quote }}
  {{- end }}
{{- end }}
